### ISSUE TITLE
Winter Break

### ISSUE THREAD

**Issue by ericnbarrett** [JumpStartGeorgia/girls-that-code#18]
Howdy everyone. We had a really low turnout this week so I have decided to postpone all classes until the new year. Our next class will be on 12 January 2015. I would very much like to get a response from all the participants who plan to continue the course at that time. We wish you a happy holidays and new year. See you in 2015!

**Comment by ericnbarrett** [comment]
Just a reminder: our next class will take place on 12 January! Looking forward to coding with y'all in 2015! See you soon!

**Comment by ericnbarrett** [comment]
Dear all, please, let's meet at [JumpStart Georgia's office](maps.ge/s/FxiR) today and from now on, as we are now a manageable size and it will make things easier. If you have trouble finding the office, please call me at 595 13 92 69. Looking forward to starting again this evening. Eric

**Comment by ninendorphine** [comment]
hi everyone :) Happy new year :)

unfortunately, i don't think i can get out of work on time today (again), but i do promise to check out class notes and prepare homework for the next class :)
