### ISSUE TITLE
how to synchronize home/Documents/girls-that-code with online repository?

### ISSUE THREAD

**Issue by ingapop** [JumpStartGeorgia/girls-that-code#19]
Hello everyone,
happy New Year and all other holidays. I have a problem: I have reinstalled OS in my computer, and now I have to reconnect with github somehow. I got new ssh key, put it in my github account, so what do I do next so I could push and pull files ? I remember a comand line that had to do something with acctuall web address of girls-that-code repo, but I can't recall exact steps. Can someone walk me through this?

**Comment by ericnbarrett** [comment]
Inga,

Did you look at the wiki on the Git hub repository? Try first to follow
those instructions (the same we used at the beginning of the course) and
then, if you can't figure it out, we'll help.

**Comment by ingapop** [comment]
I did everything I could find. a) installed git b) configured ssh c) set global username and global email d) checked that config file in git directory (home/girlsthatcode/girls-that-code/.git/config ) has "url = ssh://git@github.com/JumpStartGeorgia/girls-that-code.git" in it. So what do I do next? This is what I have now, when I try to pull something: 
![screenshot from 2015-01-11 20 15 55](https://cloud.githubusercontent.com/assets/9033949/5695859/c085d59a-99ce-11e4-925c-1259c39bbf5f.png)

**Comment by ericnbarrett** [comment]
Did you create a new key? If so, did you add it to the repository?
